# Generated by Django 5.2.6 on 2025-09-25 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='heigth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weigth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters (approx).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kilograms (approx).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years (0-130).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)]),
        ),
    ]
